### ISSUE TITLE
Improvements to Meta

### ISSUE THREAD

**Issue by Foggalong** [Foggalong/Wren#10]
The meta include has already been given a spruce up from what it was in stock Minima, but could extra features I'd like to get in:

- [x] Liquid `reading_time` which rounds to the nearest minute (rather than down)
  - [x] BUG: in GitHub pages, the `reading_time` overflows and displays page content
- [x] Reddit-style 'Last modified at...' title text, rather than appending ` ~ YYYY-MM-DD`
