### ISSUE TITLE
TODO: v0.2 Beta

### ISSUE THREAD

**Issue by Foggalong** [Foggalong/Wren#2]
Before I'm happy to start using Wren for my own blog (and others) the following things need completing. When these are done I'll release the beta, v0.2 Bewick. 
# Bugs
- [x] Reading time calculator needs integrating
- [x] Crash if no catagories given with first blog
- [x] Catagory Cloud doesn't stick to the limits given
- [x] Catagory is spelt wrong **everywhere**
# Features
- [x] Switch to included HTML, CSS, XML, & PHP setup
- [x] Limit recent blogs to 5 items
- [x] Limit RSS feeds to 25 items
# Enhancements
- [x] Make comments system optional
- [x] Remove link text decorations
- [x] Needs testing with another URL
- [x] Dates still look out of place on recent blogs list
- [x] Recolour `<h4>` and `<h4.a>`
- [x] Using non-html5 'align' property
